### ISSUE TITLE
Failure in tests::quantities_macro::float::f64::rem_assign

### ISSUE THREAD

**Issue by radix** [iliekturtles/uom#48] opened 2017-12-28 06:30 UTC
rem_assign arguments -99.32110293556526 and  4.277491538217234

```
---- tests::quantities_macro::float::f64::rem_assign stdout ----
	thread 'tests::quantities_macro::float::f64::rem_assign' panicked at '[quickcheck] TEST FAILED. Arguments: (A { v: -99.32110293556526 }, A { v: 4.277491538217234 })', C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\quickcheck-0.5.0\src\tester.rs:171:27
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by iliekturtles** [comment] 2017-12-28 14:37
Duplicate of #42. All of the `rem` and `rem_assign` tests appear to have values that exceed the current precision tolerances.

**Closed by iliekturtles** 2017-12-28 14:37 UTC
