### ISSUE TITLE
Doctest failure for custom quantity

### ISSUE THREAD

**Issue by svartalf** [iliekturtles/uom#119] opened 2019-03-25 16:15 UTC
I've created a custom quantities system and for some weird reasons doc example for the `quantity!` macro somehow breaks the documentation tests in my crate with the following error:

```
$ cargo test --all
..

failures:

---- <::uom::system::system macros> - IEC (line 803) stdout ----
error[E0432]: unresolved import `mks`
  --> doctest.rs:861:5
   |
59 |     Q!(mks, f32/*, (centimeter, gram, second)*/);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `mks` external crate
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

thread '<::uom::system::system macros> - IEC (line 803)' panicked at 'couldn't compile the test', src/librustdoc/test.rs:351:13
```

Commenting [these lines](https://github.com/iliekturtles/uom/blob/54cc327ca2778c2c229c6c1c0c486d3ae4ddc973/src/system.rs#L1457-L1459) in the `uom` sources removes an error completely.

`rustc` version: 1.33.0
`uom` version:

```
[dependencies.uom]
version = "0.21.1"
default-features = false
features = ["autoconvert", "usize", "u64", "f64", "si", "std"]
```

I guess, doc test for exported `IEC!` macro breaks for some unknown reasons?

So, here is what makes this bug "weird": it is reproducible in the existing code, but I can't reproduce it with a new cargo project.
Unfortunately, existing code is not public (yet), so at the moment I'm failing to find the way of how to show it.

@iliekturtles, any thoughts, maybe?

**Comment by iliekturtles** [comment] 2019-03-25 17:43
This is an issue caused by `edition="2018"`. I'm able to reproduce by copying the doc example into a new project. It fails to compile with `edition="2018"` but is successful with `edition="2015"`. The `$quantities!` macro is generating code is that isn't compatible for `edition="2018"`.

Short term it looks like changing the macro invocation to `Q!(crate::mks, f32/*, (centimeter, gram, second)*/);` is compatible with both editions. Long term I want to think about having `uom` documentation being generated on the `$quantities!` macro and inserted into the caller's crate. The doc comments for this macro should should possibly be specified in the `system!` macro call.

Cross-edition tests should also be added to `uom` so that issues like this get caught in the future.

**Comment by svartalf** [comment] 2019-03-25 18:03
Yeah, this explains everything, thanks :)
I think I can manage the workaround until `uom` will be compatible with the `edition="2018"`.

Not sure if this issue should be closed now, feel free to do that.

**Comment by iliekturtles** [comment] 2019-03-25 18:13
Leave it open. I have some local changes to fix the generated code to be compatible with both editions. `uom` itself is going to remain 2015 to support older compilers but I should be able to make generated code compatible. I'll try to get the changes committed and released in the next couple days.

**Closed** 2019-03-27 22:36 UTC

**Comment by iliekturtles** [comment] 2019-03-31 02:18
[v0.22.0](https://github.com/iliekturtles/uom/releases/tag/v0.22.0) with the doc test fixes released to [crates.io](https://crates.io/crates/uom).
