### ISSUE TITLE
Allow subtracting two thermodynamic temperatures

### ISSUE THREAD

**Issue by ISibboI** [iliekturtles/uom#447] opened 2023-12-05 10:02 UTC
Hi, thanks for making uom! It has caught a few errors already in my small hobby project.

Currently, when I subtract two thermodynamic temperatures, I get the following error:

```
error[E0308]: mismatched types
   --> src\substance\water.rs:122:57
    |
122 |         let temperature_difference = self.temperature - target_temperature;
    |                                                         ^^^^^^^^^^^^^^^^^^ expected trait `Kind`, found trait `TemperatureKind`
    |
    = note: expected struct `Quantity<dyn Dimension<I = Z0, J = Z0, Kind = dyn Kind, L = Z0, M = Z0, N = Z0, T = Z0, Th = ...>, ..., ...>`
               found struct `Quantity<dyn Dimension<I = Z0, J = Z0, Kind = ..., L = ..., M = ..., N = ..., T = ..., Th = ...>, ..., ...>`
```

However, I would expect this to work and the result to be a `TemperatureInterval`.

**Comment by jacg** [comment] 2023-12-05 12:54
See

+ #380 
+ #403 
+ #289

**Comment by ISibboI** [comment] 2023-12-05 14:21
How about adding another type parameter to `Quantity` that specifies if it can be added/subbed with itself or not? Then the default add/sub impl can be made only for some default value of that type parameter, and `ThermodynamicTemperature` could get its own implementation by having another value for this type parameter.

**Comment by iliekturtles** [comment] 2024-01-19 18:47
Closing as a duplicate of #380.

**Closed by iliekturtles** 2024-01-19 18:47 UTC
