### ISSUE TITLE
Base unit type constants for stable conversion

### ISSUE THREAD

**Issue by zmrocze** [iliekturtles/uom#430] opened 2023-08-05 14:09 UTC
Hey, 
I'd like to serialize values to floats, casually:

```
let position: Length;
let position_ser : f64 = position.value;  // in base unit
```

and now to deserialize I'd just need to know the base unit for the given quantity:

```
let position_deser = Length::new::<Length::BASE_UNIT>(positition_ser);
```

would it be possible to define such a constant? or is there another way?

**Comment by iliekturtles** [comment] 2023-08-08 03:46
This is one of `uom`'s warts right now. The best way at the current time is to skip the `new` constructor and create the struct directly:

```rust
let position_deser = Length{ dimension: PhantomData, units: PhantomData, value: position_ser, }
```

**Comment by iliekturtles** [comment] 2023-08-11 16:22
Closing this specific issue as the problem is covered elsewhere.

**Closed by iliekturtles** 2023-08-11 16:22 UTC
