### ISSUE TITLE
Change base unit of Unit not defined in the SI Quantities System but listed as SI Unit

### ISSUE THREAD

**Issue by vpochapuis** [iliekturtles/uom#374] opened 2022-09-07 06:55 UTC
Hello,

How can we change the base unit of a Quantity which is not defined in the SI Quantities but relies on them?
For example how can one define the base unit for `electric_potential::ElectricPotential` to be `millivolt` instead of `volt`?

I need to do this in order to work with Integers and be able to use the `cmp` function and not the `partial_cmp` one.

Thanks for your help!

**Comment by iliekturtles** [comment] 2022-09-08 00:34
Thanks for the issue. Closing as a duplicate of #97 where someone has the exact same question about `millivolt`. See [this](https://github.com/iliekturtles/uom/issues/97#issuecomment-403583166) comment for the solution. Using different base units isn't very ergonomic and integer underlying storage types are not verify polished. If you run across more problems please open new issues.

**Closed by iliekturtles** 2022-09-08 00:34 UTC

**Comment by vpochapuis** [comment] 2022-09-08 00:52
Thank you for the answer! I will look into it.
Sorry that i didn't successfully found #97 before opening this issue.

And congratulations on this crate, it really is an amazing tool!
