### ISSUE TITLE
Implement clamp

### ISSUE THREAD

**Issue by jacg** [iliekturtles/uom#376] opened 2022-09-21 16:06 UTC
It would be useful to have `uom` support `clamp`.

My attempt at implementing it ran into problems caused by there being different definitions for 

+ `{std,core}::cmp::Ord::clamp`
+ `{f32,f64}::clamp`

and my not knowing how to treat these separately inside `uom`'s implementation.

**Comment by iliekturtles** [comment] 2022-09-22 13:38
Closing this as a duplicate of #239.

 * Want to open a draft PR with the code you trying?
 * That issue discusses MSRV issues. At this point I'm inclined to bump to 1.50 with 1.64.0 coming out today.

**Closed by iliekturtles** 2022-09-22 13:38 UTC

**Comment by jacg** [comment] 2022-09-23 10:21
Ah, sorry, I should have found #239.

Here's the draft PR: #377.
