### ISSUE TITLE
Suggestion: pass units as values

### ISSUE THREAD

**Issue by ttencate** [iliekturtles/uom#365] opened 2022-09-01 09:32 UTC
Right now, the signature of `format_args` [looks like](https://docs.rs/uom/0.33.0/uom/si/length/type.Length.html#method.format_args):

```
pub fn format_args<N>(unit: N, style: DisplayStyle) -> Arguments<Dimension, N> where
    N: Unit,
```

That is, the `unit` is passed as a value as well as a type argument, even though the value is not used. This is good for ergonomics:

```
my_length.format_args(kilometer, Abbreviation)  // Instead of my_length.format_args::<kilometer>(Abbreviation)
```

This pattern could be used more widely in this crate, in `new`, `get` and arithmetic methods `floor`, `ceil`, `round`, `trunc`, `fract`:

```
Length::new(5.0, kilometer)  // Instead of Length::<kilometer>::new(5.0)
my_length.get(kilometer)     // Instead of my_length.get::<kilometer>()
my_length.floor(kilometer)   // Instead of my_length.floor::<kilometer>()
```

The runtime cost should be zero, since all unit types are zero sized.

To enable generic use in client code where a value `unit: N` is needed but only a generic unit type `N` is available, it would be good to add a `Default` implementation on all unit types.

**Comment by iliekturtles** [comment] 2022-09-08 00:11
Thanks for the submission, however this is a duplicate of #91. While it was created a while ago, there has been some recent discussion. I'm going to close this issue.

**Closed by iliekturtles** 2022-09-08 00:11 UTC

**Comment by ttencate** [comment] 2022-09-08 07:31
Not quite the same as #91. In my suggestion, there would be no `dyn` or other runtime overhead. It's purely an ergonomical thing, and perhaps also a consistency thing because `format_args` already does this.
