### ISSUE TITLE
Physical constants?

### ISSUE THREAD

**Issue by billyrieger** [iliekturtles/uom#126] opened 2019-04-21 14:50 UTC
Thanks for this great library! I think it'd be a cool feature to have physical constants directly integrated with `uom`. Existing crates such as [`natural_constants`](https://crates.io/crates/natural_constants) and [`physical_constants`](https://crates.io/crates/physical_constants) don't use units at all and instead just have the constants as floating-point numbers.

Some considerations:

- Physical constants could be considered outside the scope of `uom` and might be better suited to being defined in their own crate (`uom-constants` perhaps).
- If constants are included in `uom`, they should probably be gated behind a feature flag.
- The values of the constants could be taken from [NIST](https://physics.nist.gov/cuu/Constants/Table/allascii.txt), but deciding which constants to include and which to ignore is also an issue.
- I'm not entirely sure how constants would interact with the different underlying storage types. Some constants are exact integers (e.g. speed of light in vacuum) whereas most are floating-point and have some uncertainty.

I'd be happy to begin work on this feature if you think it's suitable for `uom` and the above considerations are resolved.

**Comment by iliekturtles** [comment] 2019-04-21 18:54
Duplicate of #32. Closing this one and I will reply there. Definitely something I would like to see.

**Closed by iliekturtles** 2019-04-21 18:54 UTC
