### ISSUE TITLE
Implement clamp for f64 Quantities

### ISSUE THREAD

**Issue by kylecarow** [iliekturtles/uom#476] opened 2024-06-07 18:38 UTC
Recently tried to use `clamp` on an f64 quantity, but ran into this issue:

`Quantity::clamp` is only implemented via the `Ord` trait:
[`impl Ord for Quantity`](https://docs.rs/uom/latest/uom/si/struct.Quantity.html#method.clamp)

f64 and f32 implement `clamp` manually (which makes sense, as they aren't `Ord` - though I'm unsure why `clamp` couldn't have been implemented in `PartialOrd` given that it only uses `PartialOrd` comparisons, oh well)
[`f64::clamp`](https://doc.rust-lang.org/std/primitive.f64.html#method.clamp)
[`f32::clamp`](https://doc.rust-lang.org/std/primitive.f32.html#method.clamp)

Could clamp (and maybe similar methods) be implemented for f64 Quantities? This would be used widely throughout my code, where I otherwise have doubled-up min/max calls.

**Comment by iliekturtles** [comment] 2024-10-22 01:00
Closing as a duplicate of #239. Draft PR is available at #377, but I just haven't pushed it over the finish line.

**Closed by iliekturtles** 2024-10-22 01:00 UTC
